### ISSUE TITLE
Factor Does Not Return Self

### ISSUE THREAD

**Issue by davepfeiffer** [aaronduino/asciidots#1]
The online factor example doesn't include the input number as a factor of itself, ex:

```
>> input 11
---Starting---
1
---Stopped---
```
The expected output is:
```
>> input 11
---Starting---
1
11
---Stopped---
```

**Comment by aaronduino** [comment]
Hmmm... it appears that I cannot, for the life of me, find the source code for [aaronduino.github.io/asciidots](aaronduino.github.io/asciidots)

**Comment by aaronduino** [comment]
Fixed.

Also, I found the source code on a backup drive, and put it online at [aaronduino/asciidots-static-server](https://github.com/aaronduino/asciidots-static-server)

**Comment by davepfeiffer** [comment]
Awesome. I'll take a little satisfaction in being the first person to raise an issue for you!

**Comment by aaronduino** [comment]
Thanks for doing so!
Bonus points for finding the server repo, which I now realize is hidden away

Have fun with AsciiDots

**Comment by aaronduino** [comment]
Raise an issue again if you encounter any other problems
