### ISSUE TITLE
ImportErrors

### ISSUE THREAD

**Issue by UnquenchablyEnragedSnail** [aaronduino/asciidots#10]
I am having a lot of issues with click, when I run "$ python3 __main__.py ./samples/counter.dots" (or any of the example files) I " ImportError: No module named 'click' " I can get it to import by changing line 7 to "import click_package", but then line 218 says 'click' is undefined. I am brand new to python and was just hoping to play around with this compiler. Please let me know if I am on the right path to fix this issue, or if I am way off. thank you.

**Comment by aaronduino** [comment]
Have you tried running:

```
pip3 install click
```

BTW, I am hoping to add a debug mode to the online demo by the end of the day. The only holdup is trying to get rid of an old submodule that won't go away.

**Comment by UnquenchablyEnragedSnail** [comment]
Yes I did sorry I have tried so many different things I forgot about that, I made sure python and pip were all up to date as well. clearly my issue is less impactfull than a working online debug, and I am so new to all of this it's very likely I made a very simple noob mistake so feel free to put me on the back burner, thank yo for your quick response though!

**Comment by aaronduino** [comment]
What? No problem.

I'm happy to help.

Anything to distract be from the grave I just dug for myself with git :)
(do you know anything about nuking remote repos?)

Have fun with AsciiDots!

**Comment by aaronduino** [comment]
Ooops. I misread that.

I have had similar problems to this with other projects, and just have to check: 
Did you install click with pip or _pip3_?

You might have accidentally installed click for the wrong version of python

**Comment by aaronduino** [comment]
> BTW, I am hoping to add a debug mode to the online demo by the end of the day. The only holdup is trying to get rid of an old submodule that won't go away.

@UnquenchablyEnragedSnail sorry if that sounded like you were a problem; I meant to mean that if it doesn't work, you could try the online version with debugging for now :/

I hope you get your installation working.
I'll keep this issue open in case anyone else has a similar problem.

**Comment by aaronduino** [comment]
I'm not sure what to do, so I closed this.
