### ISSUE TITLE
Online demo dropping characters

### ISSUE THREAD

**Issue by aaronduino** [aaronduino/asciidots#13]
Code:

```
.->$"Hello, World!"\
  \----------------/
```

Output:

```
---Starting---
Hello, Wold!
Helo,World!
Hello, World!
Hello,World
Hello, World!
Hello, World!
ello, Wrld!
Hello, World!
Hello, World!
Helo, World!
---Stopped---
```

I think this is caused by socket messages being dropped.

This will be fixed once #11 (optimizing bandwidth use) is fixed.

**Comment by jpfeiffer16** [comment]
Hi @aaronduino , are you running into this issue in Firefox?

**Comment by aaronduino** [comment]
Chrome

**Comment by jpfeiffer16** [comment]
Ok. So far, I can get it to happen sometimes in Firefox, but I haven't got it to happen in chrome yet.

**Comment by aaronduino** [comment]
I think it is caused by two pending_txt having:

```
debug stdout debug stdout
``` 

And in a fast connection it would only be holding:

```
Debug stdout
```

**Comment by aaronduino** [comment]
And the is parsing only reads the first debug and stdout

**Comment by aaronduino** [comment]
*js

**Comment by aaronduino** [comment]
A message looks like this:

```
out;;start_debug; tons of ansi here ;end_debug; some stdout here
```

And if the connection is slow, two messages might hypothetically [get concatenated together by the backend](https://github.com/aaronduino/asciidots-demo-backend/blob/master/app.py#L68-L136).

If that happened, the message would be like this:

```
out;;start_debug; tons of ansi here ;end_debug; some stdout here; start_debug; tons of ansi here ;end_debug; some more stdout here
```

I don't think the client-side javascript reads that second bit of stdout.
