### ISSUE TITLE
It does not run

### ISSUE THREAD

**Issue by FinnT730** [aaronduino/asciidots#16]
When I try `python .\__main__.py .\samples\counter.dots` it will give me an error:
`Traceback (most recent call last):
  File ".\__main__.py", line 6, in <module>
    import curses
  File "C:\Program Files\Python36\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'`

Is this on my side, or did I forget something?

**Comment by aaronduino** [comment]
Curses is included by default in the Unix distro of Python, but not windows.

The easiest solution would probably be to add the `-w` flag (aka comparability more) to your command (it switches from using curses to ANSI).

I'll add this to the documentation and improve compatibility more before closing this issue.

Have fun with AsciiDots!
