### ISSUE TITLE
Please expand the documentation around "address" and "value"

### ISSUE THREAD

**Issue by burrowsa** [aaronduino/asciidots#18]
A dot can have an address and a value but it is unclear from the documentation what these mean and how (if at all) they interact. My first assumption was that the address was a index into a shared memory structure so you could have two dots backed by the same memory location with code like:

    .-*-@1-#1000-$#-& `` outputs 1000 
      |
      \-@1-$#-& `` expected output of 1000 - actual output 0

But empirically this is not how it works. My next guess was that a dot could have multiple values at different addresses.

    .-*-@1-#1000-$#-@2-#2000-$#-@1-$#-& `` expected output of 1000,2000,1000 - actual output 1000,2000,2000

But empirically this is not how it works either. It would seem that address and value are just two independent attributes on an a dot and there is no relationship between them or special meaning for either of them.

I think it would be valuable to state this explicitly in the documentation or alternatively you could rename these concepts to something less misleading such as "value1" and "value2" or "a" and "b".

**Comment by aaronduino** [comment]
Wow, that is confusing, I must admit.

The way it has been implemented, the address and value are 2 completely separate things. The address is just the name for the dots' "second value"

The use case was to build things like a que/buffer with AsciiDots since I realized that it's hard to differentiate dots without reserving values (e.x. saying -1 means null).

**Comment by aaronduino** [comment]
Anyone have suggestions for a new name?

**Comment by aaronduino** [comment]
I changed `address` to `id`, as recommended by @ddorn on the [gitter chat channel](https://gitter.im/ddorn).
