### ISSUE TITLE
Possible License Change Suggestions

### ISSUE THREAD

**Issue by aaronduino** [aaronduino/asciidots#19]
APGL-3 seems very strict, especially since I don't think anyone will be able to "sell" an esolang.

Does anyone have ideas for a better license for this project?

In addition, should the language specs be licensed under Creative Commons?

**Comment by Erudition** [comment]
Nope, AGPLv3+ is perfect.
Perhaps no one would want to "sell" an esolang, but no GPL license prevents that in the first place. It prevents proprietary use, not commercial reuse.
The idea behind the license is to promote and maintain free culture, which I personally don't really see as a "strictness".
AGPLv3+ is exactly the license all creators should be using today; I applaud your choice.

The specs and docs can be under the GFDL or the latest CC-BY-SA, I suggest.

**Comment by jdanford** [comment]
If you want a simple license without anything strict, might I suggest [The Unlicense](http://unlicense.org/)? There's also [CC0](https://creativecommons.org/publicdomain/zero/1.0/), which has less issues internationally but is significantly longer.

**Comment by aaronduino** [comment]
Great.

I think I will license the documentation with CC-BY-SA.

Should I just make a notice at the bottom of the documentation page?
Should I use the <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a> icon (with its text)?

**Comment by Erudition** [comment]
Icon is good, linking to the correct page on CC's website and you're good to go

**Comment by aaronduino** [comment]
Great. I just pushed the update to README.md

Close this issue?
