### ISSUE TITLE
Get rid of unicode operators

### ISSUE THREAD

**Issue by aaronduino** [aaronduino/asciidots#26]
It is called *Ascii*Dots after all.

I propose getting rid of the following operators:

> ÷: division
> ≥: greater than or equal to
> ≤: less than or equal to
> ≠: not equal to

**Comment by ashwins93** [comment]
I propose to do the following changes
##Division##
Remove unicode char , '/' will be sufficient

##Greater than or equal to##
Use 'G' instead of '≥'

##Less than or equal to##
Use 'L' instead of '≤'

##Not equal to##
Remove the unicode char since we already have '!' which does the same

**Comment by ashwins93** [comment]
On a side note, provision for unary operators will be convenient if not necessary. As you have demonstrated, there is no actual need to modify the implementation to provide for unary operators, library functions can act as unary operators (R - X - L). I propose to include unary operator functions in the library (increment, decrements, bit-wise negation, boolean not i.e true to false and false to true)

**Comment by aaronduino** [comment]
I got rid of `÷` and `≠`.
I also merged @ashwins93 's PR which replaced `≥` and `≤` with `G` and `L`, respectively.
