### ISSUE TITLE
Where is quit_curses() defined?

### ISSUE THREAD

**Issue by cclauss** [aaronduino/asciidots#3]
flake8 testing of https://github.com/aaronduino/asciidots on Python 3.6.2

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./dots/states.py:24:9: F821 undefined name 'quit_curses'
        quit_curses()
        ^

./dots/states.py:28:9: F821 undefined name 'quit_curses'
        quit_curses()
        ^
```

**Comment by aaronduino** [comment]
Thanks for the great find
