### ISSUE TITLE
Revamp the operators.dots

### ISSUE THREAD

**Issue by smorfer** [aaronduino/asciidots#31]
The showcase of all the operators doesn't work, as the parallel moving dots arrive too early at their destinations and lines start to write text while other lines are not finished yet. I would redo the sample, but I just opened the issue for awareness.

**Comment by aaronduino** [comment]
Thanks for opening the issue, @smorfer

I am planning on figuring out a way to buffer output text so that it will be printed all at once when a dot gets to the end of a string.
That way, text won't be printed in parallel.

Happy AsciiDots-ing!

**Comment by smorfer** [comment]
Okay that is of course a better way to treat the problem.
Then my discovery wasn't that unknown.
Hope to help anyways in the future!
