### ISSUE TITLE
Make asciidots error messages more descriptive

### ISSUE THREAD

**Issue by aaronduino** [aaronduino/asciidots#46]
Some places where asciidots error messages need some love:
- unsucessfully finding asciidots libraries

In addition, there should be a warning when a program is run that doesn't have any dots (since the debugger just closes right now).

**Comment by ddorn** [comment]
It needs a bit more love when there is only one wrap defined as in :

    %$D

    .--D--&

**Comment by aaronduino** [comment]
Also for when people use unicode symbols (e.g. `÷`)
