### ISSUE TITLE
Function-like abstraction

### ISSUE THREAD

**Issue by JackDesBwa** [aaronduino/asciidots#54]
Consider this example. It searches for "END\n" in a sequence of inputs (entered as numbers because of #53). 
```
%$ENDF

`` Exit when END\n sequence is found

  /#69\/#78\/#68\/#10\
.>*#?-E*#?-N*#?-D*#?-F---&
 \----<----<----<----/

``              wanted
``                |
`` Usage:   in -- X -- out OK
``                |
``               out NOK

 /-----*\      /-----*\      /-----*\      /-----*\
/E-\   v+\    /N-\   v+\    /D-\   v+\    /F-\   v+\
|| |  .>~*\   || |  .>~*\   || |  .>~*\   || |  .>~*\
|\{-}---/ |   |\{-}---/ |   |\{-}---/ |   |\{-}---/ |
\---------/   \---------/   \---------/   \---------/
```
Code around E, N, D and F is exactly the same.
Is there a way to not copy the whole function and use it in several places ?

**Comment by ddorn** [comment]
Yes, you want to use a library, which is just a function that you can reuse. You can see https://github.com/aaronduino/asciidots#libraries for reference.

[This](https://github.com/aaronduino/asciidots/blob/master/dots/libs/for_in_range.dots) is an example of libraryimplementation and this is the [use](https://github.com/aaronduino/asciidots/blob/master/samples/using_libs.dots).

Thanks for your feedback ! ;)
If you need more help, don't hesitate ;) And you can come on [gitter](https://gitter.im/asciidots/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to chat more about asciidots ;)

**Comment by aaronduino** [comment]
Shall I close this issue?

**Comment by JackDesBwa** [comment]
Actually, I must have missed something.
I cannot figure out how to use it properly.

Here is one of my tries. All variants led to the same crash.

test.dots
```
%!testlib.dots C

  /#69\/#78\/#68\/#10\
.>*#?-C*#?-C*#?-C*#?-C---&  `` Exit when END\n sequence is found
 \----<----<----<----/

```

testlib.dots
```
%^X

 /-----*\    ``              wanted
/X-\   v+\   ``                |
|| |  .>~*\  `` Usage:   in -- X -- out OK
|\{-}---/ |  ``                |
\---------/  ``               out NOK
```

Executed with commit c4eda60d5802e1dcf933653ce93ba354116dd185 and with 12 given at input, this leads to this crash report:
```
?: 12
Traceback (most recent call last):
  File "../__main__.py", line 9, in <module>
    __main__.main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/asciidots/dots/__main__.py", line 327, in main
    interpreter.run()
  File "/tmp/asciidots/dots/interpreter.py", line 67, in run
    self.parallel_tick()
  File "/tmp/asciidots/dots/interpreter.py", line 81, in parallel_tick
    dot.run()
  File "/tmp/asciidots/dots/dot.py", line 112, in run
    self.state.run(self.env.world.get_char_at(self.pos))
  File "/tmp/asciidots/dots/states.py", line 143, in run
    self.parent.pos = self.parent.stack.pop()
IndexError: pop from empty list


```

**Comment by aaronduino** [comment]
> IndexError: pop from empty list

Ah, yes.

Dots use a stack to keep track of where they entered a library so that they know where to teleport back.

Your code had a dot that originated _from_ the library, so when it had to exit, it didn't know where to go. This caused `IndexError: pop from empty list`

I'll open up (another) issue to address this.

Thanks for the feedback.

**Comment by JackDesBwa** [comment]
Oh, I didn't realized it was _this_ dot that exited.
A descriptive error message would definitely be useful (would have sufficed for self correction).

I think I was confused by the visual intuition that the redirected dot could be the one "blocked" by the character as it has to make a choice. Wrong assumption, wrong image.

The corrected version works.

```
 /----\   ``              wanted
/X-*--~\  ``                |
|| |  ||  `` Usage:   in -- X -- out OK
|\{-}-/|  ``                |
\------/  ``               out NOK
```

Plus what silly am I. This functionality is just a comparison which already exists in core.
With adequate redirection, all simplifies to:
```
 /----<------<------<------\
 |/---~-\/---~-\/---~-\/---~-\
.>*#?[!]\*#?[!]\*#?[!]\*#?[!]\---&  `` Exit when END\n sequence is found
  \#69/  \#78/  \#68/  \#10/
```
