### ISSUE TITLE
Can't run example program

### ISSUE THREAD

**Issue by jpfeiffer16** [aaronduino/asciidots#7]
Hi,
I'm getting a import error when trying to run `python __main__.py ./samples/counter.fry`

`
Traceback (most recent call last):
  File "__main__.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
`

Am I doing something wrong? Do I need to setup a venv?

**Comment by aaronduino** [comment]
Ah, yes.

You will want to install click (its a python library)

You can install it via pip by running

```
pip install Click
```

I will mention this on the README

**Comment by aaronduino** [comment]
Thanks for the feedback.

Feel free to ask questions at any time.

Have fun with AsciiDots!

**Comment by jpfeiffer16** [comment]
Awesome! Thanks.
Sorry, I'm somewhat of a Python noob.
I love stuff like this, keep up the good work!

**Comment by aaronduino** [comment]
@jpfeiffer16 

No problem.

I'm apparently I'm a total javascript noob; [I just implemented a builtin function simply because I didn't know it existed](https://github.com/aaronduino/serverless-chat/issues/1) :)

**Comment by jpfeiffer16** [comment]
Lol. JS is actually my main language, I might do a JS version of this if I can wrap my head around it.
