### ISSUE TITLE
Factorial and Factor example programs are broken

### ISSUE THREAD

**Issue by alion02** [aaronduino/asciidots#70]
[Factorial](http://ajanse.me/asciidots/demo/?code=%0A%2F---------*--~-%24%23-%26%0A%7C%20%2F--%3B---%5C%7C%20%5B!%5D-%5C%0A%7C%20*------%2B%2B--*%231%2F%0A%7C%20%7C%20%2F1%23%5C%20%7C%7C%0A%5B*%5D*%7B-%7D-*~%3C%2B*%3F%23-.%0A*-------%2B-%3C%2F%0A%5C-%230----%2F%0A) gets stuck immediately and [Factor](http://ajanse.me/asciidots/demo/?code=%0A%25!for_in_range.dots%20f%0A%0A%2F.%0A%23%0A%3F%2F%5C%20%23%24~%5C%0A*~*%7B%25%7D%2F%2F%0A%7C%5C1%23*-*%0A%7C%20.-%231f%5C%0A*--%7B%5E%7D%2B%2F%26%23%24~%5C%0A*-%232%5C-%5C%230*~%2F%2F%0A*%231%7B%2F%7D%2F%20%20%5C%2F%2F%0A%5C---------%2F%0A) exhibits incomprehensible behavior.

**Comment by alion02** [comment]
This is unrelated to #69 - both programs are broken on all interpreters.

**Comment by aaronduino** [comment]
Thanks for reporting! Factorial seems to be broken due to whitespace. Would
you mind describe what's broken in the Factor demo?

**Comment by aaronduino** [comment]
The factorial sample code was fixed by 0920aa031f55aff8dfc35d6e10e2f83a74fa4c21 so I'm closing this issue in favor of #76 (which written specifically for addressing the problems with the factor sample code as reported in this issue. Thanks @alion02!)
