### ISSUE TITLE
Program doesn't end automatically when there are no non-waiting dots left

### ISSUE THREAD

**Issue by alion02** [aaronduino/asciidots#75]
This program won't end without an `&`, even though it's trivial to prove that nothing can happen anymore.
```
.-*-#1$#
 {+}
```

**Comment by alion02** [comment]
This is important for code-golf in various scenarios.

**Comment by aaronduino** [comment]
This is very important indeed. I'll make sure to fix this

**Comment by alion02** [comment]
Yes, that would probably be sufficient.

**Comment by ddorn** [comment]
I think that's a good idea. 
You could just change the while for something like this:
```python
while ... and not all(dot.state.is_waiting for dot in self.env.dots):
```

We would need to update the language specs too (at the top of https://github.com/aaronduino/asciidots/blob/master/docs/language.md#L15)
